<?php
/**
 * Created by PhpStorm.
 * User: tim
 * Date: 2016/9/6
 * Time: 14:06
 */
namespace app\modules\admin\controllers;

use yii\web\Controller;

class CustomController extends Controller
{
    public function actionGreet()
    {
        echo 1111111111;
        return $this->render('greet'); // TODO: Change the autogenerated stub
    }
}
