<?php
/**
 * Created by PhpStorm.
 * User: tim
 * Date: 2016/9/1
 * Time: 15:15
 */
namespace app\models;

use yii\base\Model;

class EntryForm extends Model
{
    public $name;
    public $email;

    public function rules()
    {
        return [
            [['name', 'email'], 'required'],
            ['email', 'email'],
        ]; // TODO: Change the autogenerated stub
    }
}
